<table width="100%" border="0" cellpadding="0" cellspacing="0">
<tr>
	<td width="20" height="20">&nbsp;</td>
	<TD width="150" align="center" bgcolor="<?php echo $col_1_a; ?>"><a href="<?php echo $admin_path; ?>/gallery/index.php?action=album&sub=manage" class="admin_hyperlink">Manage Albums</a></td>
	<td width="5">&nbsp;</td>
	<td width="150" align="center" bgcolor="<?php echo $col_2_a; ?>"><a href="<?php echo $admin_path; ?>/gallery/index.php?action=album&sub=add" class="admin_hyperlink">Add New Album</a></td>
	<td>&nbsp;</td>
</tr>
<tr>
	<td bgcolor="#dea998" height="20" colspan="5"></td>
</tr>
</table>