<table  width="100%" border="0" cellpadding="0" cellspacing="0">
<tr>
	<td width="20" height="20">&nbsp;</td>
	<TD CLASS="tbl_data" width="50" align="center" bgcolor="<?php echo $col_1_a; ?>"><a href="index.php" class="admin_hyperlink">View</a></td>
	<td width="5">&nbsp;</td>
	<td class="tbl_data" width="50" align="center" bgcolor="<?php echo $col_2_a; ?>"><a href="add_popup.php" class="admin_hyperlink">Add</a></td>
	<td>&nbsp;</td>
</tr>
<tr>
	<td bgcolor="#dea998" height="5" colspan="5">&nbsp;</td>
</tr>
</table>